name: Feature Branch Push Workflow

on:
  push:
    branches-ignore:
      - "main"

permissions:
  contents: read

jobs:
  validate-commit-messages:
    name: 🦺 Validate Commit Messages
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }} # Ensure this workflow does not run for open PRs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Commit Messages
        id: commits
        run: |
          echo "Fetching commit messages..."
          git log --format=%s HEAD~10..HEAD > commit_messages.txt
          echo "Commit messages fetched:"
          cat commit_messages.txt

      - name: Validate Commit Messages
        run: |
          echo "Validating commit messages..."
          npx commitlint --from=HEAD~10 --to=HEAD
