name: Feature Branch Push Workflow

on:
  push:
    branches-ignore:
      - "main"

permissions:
  contents: read

jobs:
  validate-commit-messages:
    name: 🦺 Validate Commit Messages
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history to ensure all commits are available

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Fetch Commit Messages
        id: commits
        run: |
          echo "Fetching commit messages..."
          git log --format=%s HEAD~10..HEAD > commit_messages.txt || git log --format=%s > commit_messages.txt
          echo "Commit messages fetched:"
          cat commit_messages.txt

      - name: Validate Commit Messages
        run: |
          echo "Validating commit messages..."
          npx commitlint --from=HEAD~10 --to=HEAD || npx commitlint --from=HEAD~1 --to=HEAD
